[package]
name = "rtp-factory"
version = "0.0.1"
authors = ["Mario Reder <mario.reder@pm.me>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rtp-factory-lib = { path = "../rtp-factory-lib" }
