name = "rtp-api"
main = "dist/index.mjs"
usage_model = 'bundled'
workers_dev = true
compatibility_date = "2023-11-01"

[build]
command = "yarn install && yarn build"

[vars]
# The necessary secrets are:
# - INDEXER_SECRET
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

[durable_objects]
bindings = [{ name = "PARTNERSHIPS", class_name = "Partnerships" }]

[[migrations]]
tag = "v1"
new_classes = ["Partnerships"]

[env.dev]
[env.dev.build]
command = "yarn install && yarn build:dev"

[env.dev.vars]

[env.dev.durable_objects]
bindings = [{ name = "PARTNERSHIPS", class_name = "Partnerships" }]

[[env.dev.migrations]]
tag = "v1"
new_classes = ["Partnerships"]
